dist: bionic
language: go
go:
  - "1.11"

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls

install:
  - make setup
  - make build

script:
  - make test
  # Coveralls is down for maintenance currently
  # - bash scripts/cover.sh

jobs:
  include:
    - stage: Build, Unit-Tests & Fuzz-Tests
      if: branch = master AND type IN (pull_request)
      go: 1.12.x
      script:
        - bash scripts/fuzzit.sh regression

    - stage: Fuzzit (Fuzzing)
      if: branch = master AND type IN (push)
      go: 1.12.x
      script:
        - bash scripts/fuzzit.sh fuzzing
