dist: bionic

stages:
  - name: Build & test
    if: type != cron

  - name: Fuzzit-Regression
    if: type != cron AND branch = master AND type IN (pull_request)

  - name: Fuzzit-Fuzzing
    if: type = cron

jobs:
  include:
    - stage: Build & test
      language: go
      go:
        - "1.11"
      before_install:
        - go get github.com/mattn/goveralls
      install:
        - make setup
        - make build
      script:
        - make test
        # Coveralls is down for maintenance currently
        # - bash scripts/cover.sh

    - stage: Fuzzit-Regression
      go: 1.12.x
      script:
        - bash scripts/fuzzit.sh regression

    - stage: Fuzzit-Fuzzing
      go: 1.12.x
      script:
        - bash scripts/fuzzit.sh fuzzing
